{{ range $k, $v := .Values.apps }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Chart.Name }}-{{$k}}
  annotations:
    k8s.v1.cni.cncf.io/networks: {{ $v.networks }}
spec:
  containers:
  - name: {{ $.Chart.Name }}-{{$k}}
    image: "soelvkaer/gogtp:{{$k}}"
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c"]
    {{ if eq $k "enb" }}
    args:
      - sleep 30;
        ./root/enb_setup.sh;
        /usr/local/bin/enb -config /root/enb.yml;
    {{ else }}
    args:
      - ./root/{{$k}}_setup.sh;
        /usr/local/bin/{{$k}} -config /root/{{$k}}.yml;
    {{ end }}
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: "3"
    volumeMounts:
    - name: gogtp-conf-{{$k}}
      mountPath: /root/
  volumes:
  - name: gogtp-conf-{{$k}}
    configMap:
      name: gogtp-conf-{{$k}}
      defaultMode: 0777
  nodeSelector:
    kubernetes.io/hostname: {{ $v.node }}
{{ end }}

{{ range $k, $v := .Values.endpoints }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Chart.Name }}-{{$k}}
  annotations:
    k8s.v1.cni.cncf.io/networks: {{ $v.networks }}
spec:
  containers:
  - name: {{ $.Chart.Name }}-{{$k}}
    image: "ubuntu:18.04"
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash","-c"]
    args: ["./root/setup.sh"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    resources:
      limits:
        cpu: "3"
    volumeMounts:
    - name: gogtp-conf-{{$k}}
      mountPath: /root/
  volumes:
  - name: gogtp-conf-{{$k}}
    configMap:
      name: gogtp-conf-{{$k}}
      defaultMode: 0777
  nodeSelector:
    kubernetes.io/hostname: {{ $v.node }}
{{ end }}
