---
apiVersion: v1
kind: ConfigMap
metadata:
  name: universal-cnf-packet-filter-{{ .Values.input.id }}
data:
  config.yaml: |
    initactions:
      - client:
          name: "packet-filtering"
          ifname: "client0"
          routes: ["10.{{ .Values.input.server }}{{ sub .Values.input.id 1 }}.3.0/24"]
          labels:
            app: "packet-filter-{{ .Values.input.id }}"
    endpoints:
    - name: "packet-filtering-{{ .Values.input.id }}"
      labels:
        app: "packet-filter-{{ .Values.input.id }}"
      ipam:
        prefixpool: "10.{{ .Values.input.server }}{{ sub .Values.input.id 1 }}.3.0/24"
        routes: ["10.60.1.0/24", "10.60.2.0/24"]
      ifname: "endpoint0"
      action:
        dpconfig:
          acls:
            - name: "acl-1"
              rules:
              - action: 2
                iprule:
                  icmp:
                    icmptyperange:
                      first: 8
                      last: 8
                    icmpcoderange:
                      first: 0
                      last: 65535
              - action: 2
                iprule:
                  tcp:
                    sourceportrange:
                      lowerport: 0
                      upperport: 65535
                    destinationportrange:
                      lowerport: 80
                      upperport: 80
              interfaces:
                ingress: ["endpoint0"]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: universal-cnf-client-{{ .Values.input.id }}
data:
  config.yaml: |
    initactions:
      - command:
          name: "vppctl"
          args: ["show", "version"]
      - client:
          name: "packet-filtering-{{ .Values.input.id }}"
          ifname: "client0"
          labels:
            app: "ucnf-client-{{ .Values.input.id }}"
