---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ucnf-gw-left
data:
  config.yaml: |
    initactions:
      - command:
          name: "vppctl"
          args: [
            "set int ip address {{ template "intf.left" . }} 10.60.1.50/24",
            "set int state {{ template "intf.left" . }} up",
            ]
    endpoints:
    - name: "packet-filtering"
      labels:
        app: "gateway-left"
      ipam:
        prefixpool: "10.60.3.0/24"
        routes: ["10.60.1.0/24"]
      ifname: "endpoint0"
  vpp.conf: |
    unix {
      nodaemon
      log /var/log/vpp/vpp.log
      full-coredump
      cli-listen /run/vpp/cli.sock
      gid vpp
      poll-sleep-usec 1000
    }

    api-trace {
      on
    }

    api-segment {
      gid vpp
    }

    socksvr {
      default
    }

    cpu {

    }

    dpdk {
      dev {{ .Values.extport.left }}
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ucnf-gw-right
data:
  config.yaml: |
    initactions:
      - command:
          name: "vppctl"
          args: [
            "set int ip address {{ template "intf.right" . }} 10.60.0.50/24",
            "set int state {{ template "intf.right" . }} up",
            ]
    endpoints:
    - name: "packet-filtering"
      labels:
        app: "gateway-right"
      ipam:
        prefixpool: "10.60.2.0/24"
        routes: ["10.60.0.0/24"]
      ifname: "endpoint0"
  vpp.conf: |
    unix {
      nodaemon
      log /var/log/vpp/vpp.log
      full-coredump
      cli-listen /run/vpp/cli.sock
      gid vpp
      poll-sleep-usec 1000
    }

    api-trace {
      on
    }

    api-segment {
      gid vpp
    }

    socksvr {
      default
    }

    cpu {

    }

    dpdk {
      dev {{ .Values.extport.right }}
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ucnf-pf
data:
  config.yaml: |
    initactions:
      - client:
          name: "packet-filtering"
          ifname: "client0"
          routes: ["10.60.4.0/24"]
          labels:
            app: "packet-filter-left"
      - client:
          name: "packet-filtering"
          ifname: "client1"
          routes: ["10.60.4.0/24"]
          labels:
            app: "packet-filter-right"
    endpoints:
    - name: "packet-filtering"
      labels:
        app: "packet-filter"
      ipam:
        prefixpool: "10.60.4.0/24"
        routes: ["10.60.3.0/24", "10.60.2.0/24", "10.60.1.0/24", "10.60.0.0/24"]
      ifname: "endpoint0"
      action:
        dpconfig:
          acls:
            - name: "acl-1"
              rules:
              - action: 2
                iprule:
                  icmp:
                    icmptyperange:
                      first: 8
                      last: 8
                    icmpcoderange:
                      first: 0
                      last: 65535
              - action: 2
                iprule:
                  tcp:
                    sourceportrange:
                      lowerport: 0
                      upperport: 65535
                    destinationportrange:
                      lowerport: 80
                      upperport: 80
              interfaces:
                ingress: ["endpoint0"]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ucnf-client
data:
  config.yaml: |
    initactions:
      - command:
          name: "vppctl"
          args: ["show", "version"]
      - client:
          name: "packet-filtering"
          ifname: "client0"
          labels:
            app: "packet-filter"
